version: '3'
networks:
    internal:

services:
    nginx:
        image: nginx:latest
        container_name: nginx
       
        ports:
          - "80:80"
        volumes:
          - ./sites:/var/www/html
          - ./config/nginx:/etc/nginx/conf.d
        depends_on:
          - php
        networks:
          - internal
    php:
        image: php:7.4-fpm
        container_name: php
        ports:
          - "9000:9000"
        volumes:
          - ./sites:/var/www/html
        networks:
          - internal
